export default {
  units: ['гр', 'порция', 'шампур', 'штука'],
  menu_sections: [
    {
      id: 0,
      title: 'Все меню',
      subsections: null,
      items: [],
    },
    {
      id: 1,
      title: 'Шаурма',
      subsections: null,
      items: [
        {
          id: 100,
          section_id: 1,
          subsection_id: null,
          title: 'Шаурма в пите',
          image: 'shaurma_pita.jpg',
          weight: 0,
          unit: 0,
          price: 150,
          description: 'Капуста, огурец, помидор, лук, зелень, острый перец, картофель фри, фирменный соус, чесночный соус. На выбор: с курицей, свининой, говядиной или мясным миксом',
          options: [
            {
              title: 'Курица',
              price: 0,
            },
            {
              title: 'Свинина',
              price: 10,
            },
            {
              title: 'Говядина',
              price: 50,
            },
            {
              title: 'Микс курица-говядина',
              price: 30,
            },
            {
              title: 'Микс курица-свинина',
              price: 30,
            },
          ],
        },
        {
          id: 101,
          section_id: 1,
          subsection_id: null,
          title: 'Шаурма в лаваше',
          image: 'shaurma.jpg',
          weight: 0,
          unit: 0,
          price: 150,
          description: 'Капуста, огурец, помидор, лук, зелень, острый перец, картофель фри, фирменный соус, чесночный соус. На выбор: с курицей, свининой, говядиной или мясным миксом',
          options: [
            {
              title: 'Курица',
              price: 0,
            },
            {
              title: 'Свинина',
              price: 10,
            },
            {
              title: 'Говядина',
              price: 50,
            },
            {
              title: 'Микс курица-говядина',
              price: 30,
            },
            {
              title: 'Микс курица-свинина',
              price: 30,
            },
          ],
        },
        {
          id: 102,
          section_id: 1,
          subsection_id: null,
          title: 'Шаурма в сырном лаваше',
          image: 'shaurma_cheese.jpg',
          weight: 0,
          unit: 0,
          price: 150,
          description: 'Капуста, огурец, помидор, лук, зелень, острый перец, картофель фри, фирменный соус, чесночный соус. На выбор: с курицей, свининой, говядиной или мясным миксом',
          options: [
            {
              title: 'Курица',
              price: 0,
            },
            {
              title: 'Свинина',
              price: 10,
            },
            {
              title: 'Говядина',
              price: 50,
            },
            {
              title: 'Микс курица-говядина',
              price: 30,
            },
            {
              title: 'Микс курица-свинина',
              price: 30,
            },
          ],
        },
      ],
    },
    {
      id: 2,
      title: 'Блюда на мангале',
      subsections: [
        {
          id: 7,
          title: 'Свинина',
          items: [
            {
              id: 200,
              section_id: 2,
              subsection_id: 7,
              title: 'Шашлык из свиной корейки',
              image: 'pork_rack.jpg',
              weight: 100,
              unit: 0,
              price: 175,
              description: 'Шашлык из свиной корейки получается мягким за счет маринада. Подается с лавашом, луком, огурцами, помидорами, зеленью и острым соусом.',
              options: null,
            },
            {
              id: 201,
              section_id: 2,
              subsection_id: 7,
              title: 'Шашлык из свиных ребер',
              image: 'pork_ribs.jpg',
              weight: 100,
              unit: 0,
              price: 175,
              description: 'Подается с лавашом, луком, огурцами, помидорами, зеленью и острым соусом.',
              options: null,
            },
            {
              id: 202,
              section_id: 2,
              subsection_id: 7,
              title: 'Шашлык из свиной шейки',
              image: 'pork_shoulder.jpg',
              weight: 100,
              unit: 0,
              price: 180,
              description: 'Подается с лавашом, луком, огурцами, помидорами, зеленью и острым соусом.',
              options: null,
            },
            {
              id: 203,
              section_id: 2,
              subsection_id: 7,
              title: 'Шашлык из свиной мякоти',
              image: 'pork_chop.jpg',
              weight: 100,
              unit: 0,
              price: 170,
              description: 'Подается с лавашом, луком, огурцами, помидорами, зеленью и острым соусом.',
              options: null,
            },
            {
              id: 204,
              section_id: 2,
              subsection_id: 7,
              title: 'Ики-бир из свинины',
              image: 'pork_iki_bir.jpg',
              weight: 1,
              unit: 1,
              price: 220,
              description: 'Шашлык с прослойками свиного жира. Подается с лавашом, луком, огурцами, помидорами, зеленью и острым соусом.',
              options: null,
            },
            {
              id: 205,
              section_id: 2,
              subsection_id: 7,
              title: 'Ассорти из свинины',
              image: 'pork_assort.jpg',
              weight: 500,
              unit: 0,
              price: 750,
              description: 'Ассорти шашлыков из свинины по 100г: корейка, шейка, ребра, мякоть, ики-бир. Подается с лавашом, луком, огурцами, помидорами, зеленью и острым соусом.',
              options: null,
            },
          ],
        },
        {
          id: 8,
          title: 'Баранина',
          items: [
            {
              id: 210,
              section_id: 2,
              subsection_id: 8,
              title: 'Шашлык из бараньей корейки',
              image: 'mutton_rack.jpg',
              weight: 100,
              unit: 0,
              price: 210,
              description: 'Подается с лавашом, луком, огурцами, помидорами, зеленью и острым соусом.',
              options: null,
            },
            {
              id: 211,
              section_id: 2,
              subsection_id: 8,
              title: 'Шашлык из бараньих ребер',
              image: 'mutton_ribs.jpg',
              weight: 100,
              unit: 0,
              price: 170,
              description: 'Подается с лавашом, луком, огурцами, помидорами, зеленью и острым соусом.',
              options: null,
            },
            {
              id: 212,
              section_id: 2,
              subsection_id: 8,
              title: 'Шашлык из бараньей мякоти',
              image: 'mutton_chop.jpg',
              weight: 100,
              unit: 0,
              price: 190,
              description: 'Подается с лавашом, луком, огурцами, помидорами, зеленью и острым соусом.',
              options: null,
            },
            {
              id: 213,
              section_id: 2,
              subsection_id: 8,
              title: 'Шашлык из бараньих семечек',
              image: 'mutton_.jpg',
              weight: 100,
              unit: 0,
              price: 180,
              description: 'Подается с лавашом, луком, огурцами, помидорами, зеленью и острым соусом.',
              options: null,
            },
            {
              id: 214,
              section_id: 2,
              subsection_id: 8,
              title: 'Ики-бир из баранины',
              image: 'mutton_iki_bir.jpg',
              weight: 100,
              unit: 0,
              price: 230,
              description: 'Шашлык из бараньей мякоти с курдючным салом. Подается с лавашом, луком, огурцами, помидорами, зеленью и острым соусом.',
              options: null,
            },
            {
              id: 205,
              section_id: 2,
              subsection_id: 7,
              title: 'Ассорти из баранины',
              image: 'mutton_assort.jpg',
              weight: 500,
              unit: 0,
              price: 950,
              description: 'Ассорти шашлыков из баранины по 100г: корейка, ребра, мякоть, семечки, ики-бир. Подается с лавашом, луком, огурцами, помидорами, зеленью и острым соусом.',
              options: null,
            },
          ],
        },
        {
          id: 9,
          title: 'Телятина',
          items: [
            {
              id: 220,
              section_id: 2,
              subsection_id: 9,
              title: 'Шашлык из телячьей вырезки',
              image: 'veal_tender.jpg',
              weight: 100,
              unit: 0,
              price: 300,
              description: 'Подается с лавашом, луком, огурцами, помидорами, зеленью и острым соусом.',
              options: null,
            },
            {
              id: 221,
              section_id: 2,
              subsection_id: 9,
              title: 'Шашлык из мякоти телятины',
              image: 'veal_chop.jpg',
              weight: 100,
              unit: 0,
              price: 190,
              description: 'Подается с лавашом, луком, огурцами, помидорами, зеленью и острым соусом.',
              options: null,
            },
            {
              id: 222,
              section_id: 2,
              subsection_id: 9,
              title: 'Шашлык из телячьей печени',
              image: 'veal_liver.jpg',
              weight: 100,
              unit: 0,
              price: 150,
              description: 'Подается с лавашом, луком, огурцами, помидорами, зеленью и острым соусом.',
              options: null,
            },
            {
              id: 220,
              section_id: 2,
              subsection_id: 9,
              title: 'Шашлык из телячьего сердца',
              image: 'veal_heart.jpg',
              weight: 100,
              unit: 0,
              price: 150,
              description: 'Подается с лавашом, луком, огурцами, помидорами, зеленью и острым соусом.',
              options: null,
            },
          ],
        },
        {
          id: 10,
          title: 'Курица',
        },
        {
          id: 11,
          title: 'Овощи',
          items: [
            {
              id: 240,
              section_id: 2,
              subsection_id: 11,
              title: 'Картошка с салом',
              image: 'potato_bacon.jpg',
              weight: 1,
              unit: 2,
              price: 130,
              description: null,
              options: null,
            },
            {
              id: 241,
              section_id: 2,
              subsection_id: 11,
              title: 'Картошка с курдюком',
              image: 'potato_bacon.jpg',
              weight: 1,
              unit: 2,
              price: 150,
              description: null,
              options: null,
            },
            {
              id: 242,
              section_id: 2,
              subsection_id: 11,
              title: 'Шампиньоны',
              image: 'champignons.jpg',
              weight: 1,
              unit: 1,
              price: 150,
              description: null,
              options: null,
            },

            {
              id: 243,
              section_id: 2,
              subsection_id: 11,
              title: 'Баклажан',
              image: 'eggplant.jpg',
              weight: 1,
              unit: 3,
              price: 50,
              description: null,
              options: null,
            },
            {
              id: 244,
              section_id: 2,
              subsection_id: 11,
              title: 'Томат',
              image: 'tomato.jpg',
              weight: 1,
              unit: 3,
              price: 100,
              description: null,
              options: null,
            },
            {
              id: 244,
              section_id: 2,
              subsection_id: 11,
              title: 'Перец',
              image: 'pepper.jpg',
              weight: 1,
              unit: 3,
              price: 50,
              description: null,
              options: [
                {
                  title: 'Сладкий',
                  price: 0,
                },
                {
                  title: 'Острый',
                  price: 30,
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 3,
      title: 'Люля-кебабы',
      subsections: null,
    },
    {
      id: 4,
      title: 'Выпечка',
      subsections: [
        {
          id: 12,
          title: 'Тандыр',
        },
        {
          id: 12,
          title: 'Печь',
        },
        {
          id: 12,
          title: 'Пицца',
        },
      ],
    },
    {
      id: 6,
      title: 'Супы',
      subsections: null,
      items: [
        {
          id: 600,
          section_id: 6,
          subsection_id: null,
          title: 'Куриный суп с лапшой',
          image: 'chicken_soup.jpg',
          weight: 300,
          unit: 0,
          price: 130,
          description: 'Куриный бульон, лапша, яйцо куриное, перец болгарский, лук репчатый, морковь, зелень',
          options: null,
        },
        {
          id: 601,
          section_id: 6,
          subsection_id: null,
          title: 'Борщ с говядиной',
          image: 'borsch.jpg',
          weight: 300,
          unit: 0,
          price: 170,
          description: 'Борщ на говяжьем бульоне, сметана, капуста, морковь, лук репчатый, картофель, свекла, чеснок, сало, пампушки',
          options: null,
        },
        {
          id: 602,
          section_id: 6,
          subsection_id: null,
          title: 'Суп дня',
          image: 'soup_day.jpg',
          weight: 300,
          unit: 0,
          price: 150,
          description: '',
          options: null,
        },
      ],
    },
  ],

};
